\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Beer and Breweries Case Study},
            pdfauthor={David Grijalva and Apurv Mittal},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Beer and Breweries Case Study}
\author{David Grijalva and Apurv Mittal}
\date{10/5/2020}

\begin{document}
\maketitle

\hypertarget{load-libraries}{%
\section{Load Libraries}\label{load-libraries}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tm) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: NLP
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyr)}
\KeywordTok{library}\NormalTok{(plyr)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:plyr':
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ---------------------------------------------------------------------- tidyverse 1.3.0 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.5.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------------------------------------- tidyverse_conflicts() --
## x ggplot2::annotate() masks NLP::annotate()
## x dplyr::arrange()    masks plyr::arrange()
## x purrr::compact()    masks plyr::compact()
## x dplyr::count()      masks plyr::count()
## x dplyr::failwith()   masks plyr::failwith()
## x dplyr::filter()     masks stats::filter()
## x dplyr::id()         masks plyr::id()
## x dplyr::lag()        masks stats::lag()
## x dplyr::mutate()     masks plyr::mutate()
## x dplyr::rename()     masks plyr::rename()
## x dplyr::summarise()  masks plyr::summarise()
## x dplyr::summarize()  masks plyr::summarize()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'caret'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     lift
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(class)}
\KeywordTok{library}\NormalTok{(e1071)}
\KeywordTok{library}\NormalTok{(data.table)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'data.table'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     transpose
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:dplyr':
## 
##     between, first, last
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(gganimate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## No renderer backend detected. gganimate will default to writing frames to separate files
## Consider installing:
## - the `gifski` package for gif output
## - the `av` package for video output
## and restarting the R session
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(GGally)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Registered S3 method overwritten by 'GGally':
##   method from   
##   +.gg   ggplot2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(ggthemes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ggthemes
\end{verbatim}

Introduction

We have evaluated the data of the Breweries across USA and various
different popular Beers with their Alcohol content (ABV) and Bitterness
level (IBU). We did a thorough analysis of the data provided and came up
with some interesting facts. We also have some recommendations following
our data analysis provided towards the end of the presentation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Load the CSVs}
\NormalTok{breweries =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Breweries.csv"}\NormalTok{)}
\NormalTok{beers =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Beers.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We analyzed the number of breweries across US. The distribution of
breweries varies significantly across the country. Colorado and
California are the states with most Breweries. While Delaware and West
Virginia are among the states with lowest number of breweries.

Below Bar chart and Heat-map gives a good pictorial representation of
the data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 1}
\CommentTok{# Filter and plot the number of breweries in each state.}
\NormalTok{breweries_per_state =}\StringTok{ }\NormalTok{breweries }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(State)}
\NormalTok{breweries_per_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(State, n), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{ ,}\DataTypeTok{stat =} \StringTok{'identity'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(State, }\DataTypeTok{label =}\NormalTok{ n, }\DataTypeTok{vjust=}\OperatorTok{-}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{color =} \StringTok{"darkred"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{''}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Number of Breweries"}\NormalTok{, }\DataTypeTok{title=}\StringTok{'Number of Breweries per State'}\NormalTok{) }\OperatorTok{+}\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{60}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{,}\DataTypeTok{size =} \DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-3-1.pdf}

Below is the Heat-map with same data with different visualization.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Building Heatmap of US for number of breweries in each state}
\NormalTok{breweries_per_state_}\DecValTok{1}\NormalTok{ =}\StringTok{ }\NormalTok{breweries_per_state}

\CommentTok{# Remove any whitespaces present in the dataset}
\NormalTok{breweries_per_state_}\DecValTok{1}\OperatorTok{$}\NormalTok{State =}\StringTok{ }\KeywordTok{trimws}\NormalTok{(breweries_per_state_}\DecValTok{1}\OperatorTok{$}\NormalTok{State,}\DataTypeTok{which=}\KeywordTok{c}\NormalTok{(}\StringTok{"both"}\NormalTok{),}\DataTypeTok{whitespace =} \StringTok{"[ ]"}\NormalTok{)}

\CommentTok{# Setup dataframe for State name lookup}
\NormalTok{lookup =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{abbr =}\NormalTok{ state.abb, }\DataTypeTok{State =}\NormalTok{ state.name)}

\CommentTok{# Merge the dataset}
\NormalTok{breweries_per_state_}\DecValTok{1}\NormalTok{ =}\StringTok{ }\KeywordTok{merge}\NormalTok{(breweries_per_state_}\DecValTok{1}\NormalTok{, lookup, }\DataTypeTok{by.x=}\StringTok{"State"}\NormalTok{, }\DataTypeTok{by.y=}\StringTok{"abbr"}\NormalTok{)}

\CommentTok{# Change the state names to lowercase}
\NormalTok{breweries_per_state_}\DecValTok{1}\OperatorTok{$}\NormalTok{StateLower =}\StringTok{ }\KeywordTok{tolower}\NormalTok{(breweries_per_state_}\DecValTok{1}\OperatorTok{$}\NormalTok{State.y)}

\NormalTok{states =}\StringTok{ }\KeywordTok{map_data}\NormalTok{(}\StringTok{"state"}\NormalTok{)}

\NormalTok{map.df =}\StringTok{ }\KeywordTok{merge}\NormalTok{(states,breweries_per_state_}\DecValTok{1}\NormalTok{, }\DataTypeTok{by.x =} \StringTok{"region"}\NormalTok{, }\DataTypeTok{by.y =}\StringTok{"StateLower"}\NormalTok{,  }\DataTypeTok{all.x=}\NormalTok{T)}
\NormalTok{map.df =}\StringTok{ }\NormalTok{map.df[}\KeywordTok{order}\NormalTok{(map.df}\OperatorTok{$}\NormalTok{order),]}

\CommentTok{# Rename the column Name}
\KeywordTok{colnames}\NormalTok{(map.df)[}\DecValTok{8}\NormalTok{] =}\StringTok{ "Num.of.Breweries"}

\CommentTok{# Plot the breweries data on US political map}
\KeywordTok{ggplot}\NormalTok{(map.df, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{long,}\DataTypeTok{y=}\NormalTok{lat,}\DataTypeTok{group=}\NormalTok{group))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_polygon}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{Num.of.Breweries))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_path}\NormalTok{()}\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_fill_gradientn}\NormalTok{(}\DataTypeTok{colours=}\KeywordTok{rev}\NormalTok{(}\KeywordTok{heat.colors}\NormalTok{(}\DecValTok{5}\NormalTok{)), }\DataTypeTok{na.value=}\StringTok{"grey90"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Breweries by State"}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_map}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-4-1.pdf}

Heat-map helps to easily identify which states are the ones with the
most breweries. The two states with the most breweries are California
and Colorado, with 39 and 47 breweries respectively.

Now, we will merge the two data sets. Snippet of merged data is provided
below. This merge results in a data-frame of 2410 rows.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 2 - Merge beer data with the breweries data }
\NormalTok{data =}\StringTok{ }\KeywordTok{merge}\NormalTok{(}\DataTypeTok{x=}\NormalTok{breweries, }\DataTypeTok{y=}\NormalTok{beers, }\DataTypeTok{by.y =}\StringTok{"Brewery_id"}\NormalTok{ , }\DataTypeTok{by.x =} \StringTok{"Brew_ID"}\NormalTok{)}
\CommentTok{# Rename the variables}
\NormalTok{data =}\StringTok{ }\NormalTok{data}\OperatorTok{%>%}\KeywordTok{rename}\NormalTok{(}\DataTypeTok{Beer.Name=}\NormalTok{Name.y, }\DataTypeTok{Brewery =}\NormalTok{ Name.x)}
\KeywordTok{nrow}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2410
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(data,}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Brew_ID            Brewery        City State     Beer.Name Beer_ID   ABV IBU
## 1       1 NorthGate Brewing  Minneapolis    MN       Pumpion    2689 0.060  38
## 2       1 NorthGate Brewing  Minneapolis    MN    Stronghold    2688 0.060  25
## 3       1 NorthGate Brewing  Minneapolis    MN   Parapet ESB    2687 0.056  47
## 4       1 NorthGate Brewing  Minneapolis    MN  Get Together    2692 0.045  50
## 5       1 NorthGate Brewing  Minneapolis    MN Maggie's Leap    2691 0.049  26
## 6       1 NorthGate Brewing  Minneapolis    MN    Wall's End    2690 0.048  19
##                                 Style Ounces
## 1                         Pumpkin Ale     16
## 2                     American Porter     16
## 3 Extra Special / Strong Bitter (ESB)     16
## 4                        American IPA     16
## 5                  Milk / Sweet Stout     16
## 6                   English Brown Ale     16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tail}\NormalTok{(data,}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Brew_ID                       Brewery          City State
## 2405     556         Ukiah Brewing Company         Ukiah    CA
## 2406     557       Butternuts Beer and Ale Garrattsville    NY
## 2407     557       Butternuts Beer and Ale Garrattsville    NY
## 2408     557       Butternuts Beer and Ale Garrattsville    NY
## 2409     557       Butternuts Beer and Ale Garrattsville    NY
## 2410     558 Sleeping Lady Brewing Company     Anchorage    AK
##                      Beer.Name Beer_ID   ABV IBU                   Style Ounces
## 2405             Pilsner Ukiah      98 0.055  NA         German Pilsener     12
## 2406         Porkslap Pale Ale      49 0.043  NA American Pale Ale (APA)     12
## 2407           Snapperhead IPA      51 0.068  NA            American IPA     12
## 2408         Moo Thunder Stout      50 0.049  NA      Milk / Sweet Stout     12
## 2409  Heinnieweisse Weissebier      52 0.049  NA              Hefeweizen     12
## 2410 Urban Wilderness Pale Ale      30 0.049  NA        English Pale Ale     12
\end{verbatim}

With the merged data, we first needs to check-out if there are any
missing values. After data evaluation, we identified that there are only
two variables with missing data. ABV is missing 62 values while IBU is
missing 1005 rows.Since its a large number of missing values we need to
identify a way to impute the missing values.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Questions 3 - Handle missing values}
\NormalTok{missing.values <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(}\DataTypeTok{key =} \StringTok{"key"}\NormalTok{, }\DataTypeTok{value =} \StringTok{"val"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{is.missing =} \KeywordTok{is.na}\NormalTok{(val)) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{group_by}\NormalTok{(key, is.missing) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{num.missing =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{filter}\NormalTok{(is.missing}\OperatorTok{==}\NormalTok{T) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{is.missing) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(num.missing))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` regrouping output by 'key' (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Plot the missing values to identify the variables with missing data.}
\NormalTok{missing.values }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{key, }\DataTypeTok{y=}\NormalTok{num.missing), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{,}\DataTypeTok{stat =} \StringTok{'identity'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(key, }\DataTypeTok{label =}\NormalTok{ num.missing, }\DataTypeTok{vjust=}\OperatorTok{-}\FloatTok{0.2}\NormalTok{),}\DataTypeTok{size =} \DecValTok{4}\NormalTok{, }\DataTypeTok{color =} \StringTok{"white"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{''}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Number of missing values"}\NormalTok{, }\DataTypeTok{title=}\StringTok{'Number of missing values'}\NormalTok{) }\OperatorTok{+}\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}
\StringTok{   }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{0}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-6-1.pdf}

Next we plot IBU and ABV distribution.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Questions 3 - Handle missing values}

\CommentTok{# Plot ABV distribution}
\NormalTok{data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{ABV), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\OperatorTok{+}\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}
\StringTok{   }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"ABV"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Count"}\NormalTok{, }\DataTypeTok{title=}\StringTok{"ABV Distribution"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 62 rows containing non-finite values (stat_bin).
\end{verbatim}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Plot IBU distribution}
\NormalTok{data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{IBU), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\OperatorTok{+}\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}
\StringTok{   }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"IBU"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Count"}\NormalTok{, }\DataTypeTok{title=}\StringTok{"IBU Distribution"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1005 rows containing non-finite values (stat_bin).
\end{verbatim}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-7-2.pdf}

Quick visual inspection into the distribution of each variable, we
notice that IBU is highly right skewed while ABV is slightly skewed.

Each type of beer style has its unique bitterness which might vary a bit
from brand to brand but will still be in same ballpark for the beer
style. There are 100 beer styles and more than 1,000 missing values we
felt that the best approach was not to impute the missing IBU with the
median IBU from all the known data for IBU, instead we decided to impute
the missing values with medians for ABV, while for IBU we calculated the
median for each beer style and imputed missing data with the median IBU
value for that style.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Get rid of special characters in the beer styles}
\NormalTok{data}\OperatorTok{$}\NormalTok{Style =}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"[^0-9A-Za-z' ]"}\NormalTok{,}\StringTok{" "}\NormalTok{ , data}\OperatorTok{$}\NormalTok{Style ,}\DataTypeTok{ignore.case =} \OtherTok{TRUE}\NormalTok{)}

\CommentTok{#Deal with NA in IBU}
\CommentTok{# Finds the median value per beer style}
\NormalTok{meanIBU =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{nrow =} \DecValTok{100}\NormalTok{)}
\NormalTok{styles =}\StringTok{ }\KeywordTok{list}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(data}\OperatorTok{$}\NormalTok{Style)) )}
\NormalTok{\{}
\NormalTok{  beer_style =}\StringTok{ }\KeywordTok{unique}\NormalTok{(data}\OperatorTok{$}\NormalTok{Style)[i]}
\NormalTok{  ibu_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(data[}\KeywordTok{grep}\NormalTok{(beer_style, data}\OperatorTok{$}\NormalTok{Style, }\DataTypeTok{ignore.case =}\NormalTok{ T),]}\OperatorTok{$}\NormalTok{IBU,}\DataTypeTok{na.rm =}\NormalTok{ T )}
\NormalTok{  meanIBU[i] =}\StringTok{ }\NormalTok{ibu_mean}
\NormalTok{  styles[[i]] =}\StringTok{ }\NormalTok{beer_style}
\NormalTok{\}}

\CommentTok{# Create a new styles dataframe with the IBU medians per beer style}
\NormalTok{styles_impute =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{IBU=}\NormalTok{meanIBU, }\DataTypeTok{Style =} \KeywordTok{matrix}\NormalTok{(}\KeywordTok{unlist}\NormalTok{(styles), }\DataTypeTok{nrow=}\KeywordTok{length}\NormalTok{(styles), }\DataTypeTok{byrow=}\NormalTok{T))}

\CommentTok{# merge the beer styles median IBU dataframe with the working dataframe on style name }
\NormalTok{impute_data =}\StringTok{ }\KeywordTok{merge}\NormalTok{(data, styles_impute, }\DataTypeTok{by.x=}\StringTok{"Style"}\NormalTok{, }\DataTypeTok{by.y=}\StringTok{"Style"}\NormalTok{) }

\CommentTok{# If NA in original IBU value, then use median IBU per style, else use original value }
\NormalTok{impute_data =}\StringTok{ }\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{imputed_IBU =} \KeywordTok{ifelse}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(IBU.x) }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{,IBU.y,IBU.x))}
\CommentTok{# Impute any impute_data value with the median for the ABV and imputed_IBU columns}
\NormalTok{impute_data=}\StringTok{ }\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate_at}\NormalTok{(}\KeywordTok{vars}\NormalTok{(ABV,imputed_IBU),}\OperatorTok{~}\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(.x), }\KeywordTok{median}\NormalTok{(.x, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{), .x))}

\CommentTok{# Get rid of the 5 rows without a beer style. }
\NormalTok{impute_data =}\StringTok{ }\NormalTok{impute_data}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{Style}\OperatorTok{==}\StringTok{""}\NormalTok{)}

\CommentTok{# Drop redundant columns}
\NormalTok{drops =}\StringTok{  }\KeywordTok{c}\NormalTok{(}\StringTok{"IBU.x"}\NormalTok{,}\StringTok{"IBU.y"}\NormalTok{)}
\NormalTok{impute_data =}\StringTok{ }\NormalTok{impute_data[ , }\OperatorTok{!}\NormalTok{(}\KeywordTok{names}\NormalTok{(impute_data) }\OperatorTok{%in%}\StringTok{ }\NormalTok{drops)]}
\end{Highlighting}
\end{Shaded}

There were also 5 beers with a missing style. We decided to drop those
records.

Next, we computed the median Alcohol content (ABV) and median Bitterness
(IBU) fir each state.

Median IBU by state:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 4 - Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.}

\CommentTok{# Calculate Median IBU}

\NormalTok{median_ibu_state =}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(impute_data[, }\DecValTok{10}\NormalTok{], }\KeywordTok{list}\NormalTok{(impute_data}\OperatorTok{$}\NormalTok{State), median)}

\CommentTok{# Plot median IBU by state}
\NormalTok{median_ibu_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(Group}\FloatTok{.1}\NormalTok{, x),}\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{, }\DataTypeTok{stat =} \StringTok{'identity'}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{''}\NormalTok{, }\DataTypeTok{y=}\StringTok{"IBU Value"}\NormalTok{, }\DataTypeTok{title=}\StringTok{'IBU by State'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{60}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{, }\DataTypeTok{size=}\DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-9-1.pdf}

Median ABV by State:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Calculate Median ABV}
\NormalTok{median_abv_state =}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(impute_data[, }\DecValTok{8}\NormalTok{], }\KeywordTok{list}\NormalTok{(impute_data}\OperatorTok{$}\NormalTok{State), median)}

\CommentTok{# Plot Median ABV by State}
\NormalTok{median_abv_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(Group}\FloatTok{.1}\NormalTok{, x), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{, }\DataTypeTok{stat =} \StringTok{'identity'}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{''}\NormalTok{, }\DataTypeTok{y=}\StringTok{"ABV Value"}\NormalTok{, }\DataTypeTok{title=}\StringTok{'ABV by State'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{60}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{, }\DataTypeTok{size =} \DecValTok{6}\NormalTok{ ))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-10-1.pdf}

Delaware and West Virginia are by far leading on the IBU and New
Hampshire among the lowest.

In terms of alcohol content West Virginia is leading again which gives
an impression there could be a relationship between the IBU and ABV.

Next we identified the states with a Beer with highest Alcohol content
(ABV) and Beer with most bitterness.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 5 - Which state has the maximum alcoholic (ABV) beer? }

\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(ABV}\OperatorTok{==}\KeywordTok{max}\NormalTok{(ABV))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Style Brew_ID                 Brewery    City State
## 1 Quadrupel  Quad       52 Upslope Brewing Company Boulder    CO
##                                              Beer.Name Beer_ID   ABV Ounces
## 1 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale    2565 0.128   19.2
##   imputed_IBU
## 1          24
\end{verbatim}

The state with the maximum ABV in a beer is CO. The beer is the Lee Hill
Series Vol. 5 - Belgian Style Quadruple Ale with an ABV of 0.128.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 5 -Which state has the most bitter (IBU) beer?}

\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(imputed_IBU}\OperatorTok{==}\KeywordTok{max}\NormalTok{(imputed_IBU))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            Style Brew_ID                 Brewery    City State
## 1 American Double   Imperial IPA     375 Astoria Brewing Company Astoria    OR
##                   Beer.Name Beer_ID   ABV Ounces imputed_IBU
## 1 Bitter Bitch Imperial IPA     980 0.082     12         138
\end{verbatim}

The state with the maximum IBU in a beer is OR. The beer is the Bitter
Bitch Imperial IPA with an IBU of 138.

Next, we calculated the mean, max and median of ABV across the states.
Also, checked the distribution,

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 6 - Comment on the summary statistics and distribution of the ABV variable.}
\CommentTok{# Calculate Summary}
\KeywordTok{summary}\NormalTok{(impute_data}\OperatorTok{$}\NormalTok{ABV)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00100 0.05000 0.05600 0.05968 0.06700 0.12800
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Histogram for Distribution}
\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(ABV), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'ABV Value'}\NormalTok{, }\DataTypeTok{y=}\StringTok{"count"}\NormalTok{, }\DataTypeTok{title=}\StringTok{'ABV Distribution'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Boxplot for distribution}
\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(ABV), }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'ABV Value'}\NormalTok{, }\DataTypeTok{title=}\StringTok{'ABV Boxplot'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-13-2.pdf}

It appears that the distribution of the ABV variable is slightly right
skewed. There appears to be outliers particularly on the left side as
ABV is almost zero.\\
Min: 0.10\% , Median: 5.60\% , Mean: 5.96\% , Max: 12.80\%

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 7 - Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer.}

\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{ABV, }\DataTypeTok{y=}\NormalTok{imputed_IBU), }\DataTypeTok{color=}\StringTok{"steelblue"}\NormalTok{, }\DataTypeTok{size =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{ABV, }\DataTypeTok{y=}\NormalTok{imputed_IBU),}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'ABV Value'}\NormalTok{, }\DataTypeTok{y=}\StringTok{"IBU Value"}\NormalTok{, }\DataTypeTok{title=}\StringTok{"Relation between IBU and ABV"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{,}\DataTypeTok{x=}\FloatTok{0.12}\NormalTok{, }\DataTypeTok{y=}\DecValTok{135}\NormalTok{, }\DataTypeTok{label=}\StringTok{"Correlation: 58.00%"}\NormalTok{, }\DataTypeTok{color=}\StringTok{"darkred"}\NormalTok{, }\DataTypeTok{size=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(impute_data}\OperatorTok{$}\NormalTok{ABV, impute_data}\OperatorTok{$}\NormalTok{imputed_IBU, }\DataTypeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5802225
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm1<-}\KeywordTok{lm}\NormalTok{(ABV}\OperatorTok{~}\NormalTok{imputed_IBU, }\DataTypeTok{data =}\NormalTok{ impute_data)}
\KeywordTok{summary}\NormalTok{(lm1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = ABV ~ imputed_IBU, data = impute_data)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.056510 -0.006384 -0.002144  0.004060  0.073830 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 4.627e-02  4.438e-04  104.25   <2e-16 ***
## imputed_IBU 3.291e-04  9.423e-06   34.92   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.01091 on 2403 degrees of freedom
## Multiple R-squared:  0.3367, Adjusted R-squared:  0.3364 
## F-statistic:  1220 on 1 and 2403 DF,  p-value: < 2.2e-16
\end{verbatim}

From looking at the scatter-plot above it seems that there is a positive
linear relation between ABV and IBU variables. As the ABV the increases
the IBU is expected to increase as well. Correlation coefficient of
58.02\% explains the variability in IBU based on the changes in ABV.
This suggest some evidence that the more alcohol content in the beer the
bitter it will be which can be associated to the fact that more
bitterness requires breweries to add sweetness to the beer to balance
the taste and additional sugar leads to higher alcohol. Which makes it
apparent that increase in IBU leads to increase in ABV and vice versa.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 8 - Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.}

\CommentTok{# Create new ipa_ale column based on regex from the beer style column}

\NormalTok{impute_data}\OperatorTok{$}\NormalTok{ipa_ale =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{grepl}\NormalTok{(}\StringTok{"ipa"}\NormalTok{, impute_data}\OperatorTok{$}\NormalTok{Style, }\DataTypeTok{ignore.case =}\NormalTok{ T), }\StringTok{"ipa"}\NormalTok{, }
         \KeywordTok{ifelse}\NormalTok{(}\KeywordTok{grepl}\NormalTok{(}\StringTok{"ale"}\NormalTok{, impute_data}\OperatorTok{$}\NormalTok{Style, }\DataTypeTok{ignore.case =}\NormalTok{ T), }\StringTok{"ale"}\NormalTok{, }\StringTok{"Other"}\NormalTok{))}
\CommentTok{# Filter out other type}
\NormalTok{ale_ipa =}\StringTok{ }\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{ipa_ale}\OperatorTok{==}\StringTok{"Other"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

To assess the relation between IBU and ABV between IPA and Ales we will
first need to create a variable with classifies the beers between
``Ale'', ``IPA'', and ``other''. We will then filter out the ``other''
variable from the data set. This will result in a data set containing
only ``ALE'' and ``IPA'' labels.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Choose the best K}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{12}\NormalTok{)}
\NormalTok{splitPerc =}\StringTok{ }\FloatTok{.70}

\CommentTok{# Split the dataset into train and test}
\NormalTok{trainIndices =}\StringTok{ }\KeywordTok{sample}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{],}\KeywordTok{round}\NormalTok{(splitPerc }\OperatorTok{*}\StringTok{ }\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{]))}
\NormalTok{train =}\StringTok{ }\NormalTok{ale_ipa[trainIndices,]}
\NormalTok{test =}\StringTok{ }\NormalTok{ale_ipa[}\OperatorTok{-}\NormalTok{trainIndices,]}

\CommentTok{# Run iterations to find the best K}
\NormalTok{iterations =}\StringTok{ }\DecValTok{50}
\NormalTok{accs =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{accuracy =} \KeywordTok{numeric}\NormalTok{(iterations), }\DataTypeTok{k =} \KeywordTok{numeric}\NormalTok{(iterations))}

\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{iterations)}
\NormalTok{\{}
  
\NormalTok{  classification =}\StringTok{ }\KeywordTok{knn}\NormalTok{(train[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)], test[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)],train}\OperatorTok{$}\NormalTok{ipa_ale,}\DataTypeTok{k=}\NormalTok{i)}
\NormalTok{  cm =}\StringTok{ }\KeywordTok{confusionMatrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(test}\OperatorTok{$}\NormalTok{ipa_ale, classification ), }\DataTypeTok{positive=}\StringTok{"ale"}\NormalTok{)}
  

\NormalTok{  accs}\OperatorTok{$}\NormalTok{accuracy[i] =}\StringTok{ }\NormalTok{cm}\OperatorTok{$}\NormalTok{overall[}\DecValTok{1}\NormalTok{]}
\NormalTok{  accs}\OperatorTok{$}\NormalTok{k[i] =}\StringTok{ }\NormalTok{i}
\NormalTok{\}}

\CommentTok{# Plot the K values with accuracy variation}

\KeywordTok{plot}\NormalTok{(accs}\OperatorTok{$}\NormalTok{k,accs}\OperatorTok{$}\NormalTok{accuracy, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Value of k"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Accuracy Percentage"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Best Value of K"}\NormalTok{)}
\KeywordTok{axis}\NormalTok{(}\DataTypeTok{side =} \DecValTok{2}\NormalTok{, }\DataTypeTok{at =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\OperatorTok{:}\DecValTok{50}\NormalTok{, }\DecValTok{5}\NormalTok{))}
\KeywordTok{box}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-16-1.pdf}

We ran 50 iterations of the K-NN (K nearest neighbors) classier to
choose the K with the highest accuracy classifying between ``ALE'' and
``IPA''. It appears that the best value K with highest accuracy is 5. We
will use K = 5 to run different train/test splits.

The Accuracy, specificity and sensitivity measures are quite high for
K=5. Accuracy is at 90\%.Specificity and Sensitivity at 87.0\% and
92.0\% respectively.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Run 1000 iterations  on different train/test sets. We will compute the average accuracy, specificity and Sensitivity.}
\NormalTok{iterations =}\StringTok{ }\DecValTok{1000}
\NormalTok{masterAcc =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{nrow =}\NormalTok{ iterations)}
\NormalTok{masterSensitivity =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{nrow =}\NormalTok{ iterations)}
\NormalTok{masterSpecificity =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{nrow =}\NormalTok{ iterations)}
\NormalTok{splitPerc =}\StringTok{ }\FloatTok{.7} \CommentTok{#Training / Test split Percentage}
\ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{iterations)}
\NormalTok{\{}
\NormalTok{  splitPerc =}\StringTok{ }\FloatTok{.70}
  \KeywordTok{set.seed}\NormalTok{(j}\OperatorTok{*}\DecValTok{49}\OperatorTok{+}\DecValTok{15}\NormalTok{)}
\NormalTok{  trainIndices =}\StringTok{ }\KeywordTok{sample}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{],}\KeywordTok{round}\NormalTok{(splitPerc }\OperatorTok{*}\StringTok{ }\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{]))}
\NormalTok{  train =}\StringTok{ }\NormalTok{ale_ipa[trainIndices,]}
\NormalTok{  test =}\StringTok{ }\NormalTok{ale_ipa[}\OperatorTok{-}\NormalTok{trainIndices,]}
  
\NormalTok{  classification =}\StringTok{ }\KeywordTok{knn}\NormalTok{(train[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)], test[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)],train}\OperatorTok{$}\NormalTok{ipa_ale,}\DataTypeTok{k=}\DecValTok{5}\NormalTok{)}
\NormalTok{  cm =}\StringTok{ }\KeywordTok{confusionMatrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(test}\OperatorTok{$}\NormalTok{ipa_ale, classification ), }\DataTypeTok{positive=}\StringTok{"ale"}\NormalTok{)}
  
  
\NormalTok{  masterAcc[j] =}\StringTok{ }\NormalTok{cm}\OperatorTok{$}\NormalTok{overall[}\DecValTok{1}\NormalTok{]}
\NormalTok{  masterSpecificity[j] =}\StringTok{ }\NormalTok{cm}\OperatorTok{$}\NormalTok{byClass[}\DecValTok{2}\NormalTok{]}
\NormalTok{  masterSensitivity[j] =}\StringTok{ }\NormalTok{cm}\OperatorTok{$}\NormalTok{byClass[}\DecValTok{1}\NormalTok{]}
  
\NormalTok{\}}


\NormalTok{MeanAcc =}\StringTok{ }\KeywordTok{colMeans}\NormalTok{(masterAcc)}
\NormalTok{MeanSpecificity =}\StringTok{ }\KeywordTok{colMeans}\NormalTok{(masterSpecificity)}
\NormalTok{MeanSensitivity =}\StringTok{ }\KeywordTok{colMeans}\NormalTok{(masterSensitivity)}

\NormalTok{MeanAcc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9048203
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MeanSpecificity}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8699283
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MeanSensitivity}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9247805
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{splitPerc =}\StringTok{ }\FloatTok{.70}
\KeywordTok{set.seed}\NormalTok{(j}\OperatorTok{*}\DecValTok{49}\OperatorTok{+}\DecValTok{15}\NormalTok{)}
\NormalTok{trainIndices =}\StringTok{ }\KeywordTok{sample}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{],}\KeywordTok{round}\NormalTok{(splitPerc }\OperatorTok{*}\StringTok{ }\KeywordTok{dim}\NormalTok{(ale_ipa)[}\DecValTok{1}\NormalTok{]))}
\NormalTok{train =}\StringTok{ }\NormalTok{ale_ipa[trainIndices,]}
\NormalTok{test =}\StringTok{ }\NormalTok{ale_ipa[}\OperatorTok{-}\NormalTok{trainIndices,]}
  
  

\CommentTok{# Do knn}
\NormalTok{fit =}\StringTok{ }\KeywordTok{knn}\NormalTok{(train[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)], test[,}\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{)],train}\OperatorTok{$}\NormalTok{ipa_ale,}\DataTypeTok{k=}\DecValTok{5}\NormalTok{)}

\CommentTok{# Create a dataframe to simplify charting}
\NormalTok{plot.df =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(test, }\DataTypeTok{predicted =}\NormalTok{ fit)}
\NormalTok{plot.df}\OperatorTok{$}\NormalTok{ipa_ale =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(plot.df}\OperatorTok{$}\NormalTok{ipa_ale)}


\CommentTok{# First use Convex hull to determine boundary points of each cluster}
\NormalTok{plot.df1 =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ plot.df}\OperatorTok{$}\NormalTok{imputed_IBU, }
                      \DataTypeTok{y =}\NormalTok{ plot.df}\OperatorTok{$}\NormalTok{ABV, }
                      \DataTypeTok{predicted =}\NormalTok{ plot.df}\OperatorTok{$}\NormalTok{predicted)}

\NormalTok{find_hull =}\StringTok{ }\ControlFlowTok{function}\NormalTok{(df) df[}\KeywordTok{chull}\NormalTok{(df}\OperatorTok{$}\NormalTok{x, df}\OperatorTok{$}\NormalTok{y), ]}
\NormalTok{boundary =}\StringTok{ }\KeywordTok{ddply}\NormalTok{(plot.df1, }\DataTypeTok{.variables =} \StringTok{"predicted"}\NormalTok{, }\DataTypeTok{.fun =}\NormalTok{ find_hull)}

\KeywordTok{ggplot}\NormalTok{(plot.df, }\KeywordTok{aes}\NormalTok{(imputed_IBU, ABV, }\DataTypeTok{color =}\NormalTok{ predicted, }\DataTypeTok{fill =}\NormalTok{ predicted)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{size =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{   }\KeywordTok{geom_polygon}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ boundary, }\KeywordTok{aes}\NormalTok{(x,y), }\DataTypeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"KNN Clusters Prediction Boundaries"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"IBU"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# plot source: https://stackoverflow.com/questions/35402850/how-to-plot-knn-clusters-boundaries-in-r}
\end{Highlighting}
\end{Shaded}

From the above plots its evident that ABV and IBU are correlated and
varies significantly for IPA and ALEs. We can see a clear trend that the
higher value of IBU is associated to IPAs while smaller values of IBU
associated to ALEs. There is middle ground where IPAs and ALEs both
overlap for the same level of IBUs and ABV but that area is
comparatively small. There is a clear distinction between ALE and IPAs
based on the IBU and ABV values.

Since, we know that IPAs and ALEs are clearly different and have
different properties. We took our analysis to the next step. We checked
the most popular words among the Beer Styles and among Beer Names.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Question 9 - Knock their socks off!  Find one other useful inference from the data that you feel Budweiser may be able to find value in.  You must convince them why it is important and back up your conviction with appropriate statistical evidence. }

\KeywordTok{library}\NormalTok{(wordcloud)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: RColorBrewer
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#install.packages("RColorBrewer")}
\KeywordTok{library}\NormalTok{(RColorBrewer)}
\CommentTok{#install.packages("wordcloud2")}
\KeywordTok{library}\NormalTok{(wordcloud2)}
\CommentTok{#install.packages("tm")}
\KeywordTok{library}\NormalTok{(tm)}

\CommentTok{# Set Beer Style as Vector}
\NormalTok{text =}\StringTok{ }\KeywordTok{as.vector}\NormalTok{(impute_data[}\StringTok{'Style'}\NormalTok{])}
\NormalTok{docs =}\StringTok{ }\KeywordTok{Corpus}\NormalTok{(}\KeywordTok{VectorSource}\NormalTok{(text))}

\CommentTok{# Remove punctuations, whitespaces and numbers}
\NormalTok{docs =}\StringTok{ }\NormalTok{docs }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(removeNumbers) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(removePunctuation) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(stripWhitespace)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., removeNumbers): transformation drops documents
\end{verbatim}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., removePunctuation): transformation drops
## documents
\end{verbatim}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., stripWhitespace): transformation drops
## documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Move to lower case}
\NormalTok{docs =}\StringTok{ }\KeywordTok{tm_map}\NormalTok{(docs, }\KeywordTok{content_transformer}\NormalTok{(tolower))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(docs, content_transformer(tolower)):
## transformation drops documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Ignore Stop Words}
\NormalTok{docs =}\StringTok{ }\KeywordTok{tm_map}\NormalTok{(docs, removeWords, }\KeywordTok{stopwords}\NormalTok{(}\StringTok{"english"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(docs, removeWords, stopwords("english")):
## transformation drops documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tdm =}\StringTok{ }\KeywordTok{TermDocumentMatrix}\NormalTok{(docs) }
\NormalTok{matrix =}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(tdm) }
\NormalTok{words =}\StringTok{ }\KeywordTok{sort}\NormalTok{(}\KeywordTok{rowSums}\NormalTok{(matrix),}\DataTypeTok{decreasing=}\OtherTok{TRUE}\NormalTok{) }

\CommentTok{# Make a dataframe}
\NormalTok{df_style =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{word =} \KeywordTok{names}\NormalTok{(words),}\DataTypeTok{freq=}\NormalTok{words)}

\CommentTok{# Set Beer Name as Vector}
\NormalTok{text =}\StringTok{ }\KeywordTok{as.vector}\NormalTok{(impute_data}\OperatorTok{$}\NormalTok{Beer.Name)}
\NormalTok{docs =}\StringTok{ }\KeywordTok{Corpus}\NormalTok{(}\KeywordTok{VectorSource}\NormalTok{(text))}

\CommentTok{# Remove punctuations, whitespaces and numbers}
\NormalTok{docs =}\StringTok{ }\NormalTok{docs }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(removeNumbers) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(removePunctuation) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{tm_map}\NormalTok{(stripWhitespace)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., removeNumbers): transformation drops documents
\end{verbatim}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., removePunctuation): transformation drops
## documents
\end{verbatim}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(., stripWhitespace): transformation drops
## documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{docs =}\StringTok{ }\KeywordTok{tm_map}\NormalTok{(docs, }\KeywordTok{content_transformer}\NormalTok{(tolower))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(docs, content_transformer(tolower)):
## transformation drops documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Ignore Stop Words}
\NormalTok{docs =}\StringTok{ }\KeywordTok{tm_map}\NormalTok{(docs, removeWords, }\KeywordTok{stopwords}\NormalTok{(}\StringTok{"english"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in tm_map.SimpleCorpus(docs, removeWords, stopwords("english")):
## transformation drops documents
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tdm =}\StringTok{ }\KeywordTok{TermDocumentMatrix}\NormalTok{(docs) }

\NormalTok{matrix =}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(tdm) }
\NormalTok{words =}\StringTok{ }\KeywordTok{sort}\NormalTok{(}\KeywordTok{rowSums}\NormalTok{(matrix),}\DataTypeTok{decreasing=}\OtherTok{TRUE}\NormalTok{) }

\CommentTok{# Make a dataframe}
\NormalTok{df_name =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{word =} \KeywordTok{names}\NormalTok{(words),}\DataTypeTok{freq=}\NormalTok{words)}
\end{Highlighting}
\end{Shaded}

Word Cloud - Beer Styles

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Create the Word cloud of Beer Style}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ df_style}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ df_style}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \DecValTok{1}\NormalTok{,}\DataTypeTok{max.words=}\DecValTok{100}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{,}\DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{8}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-20-1.pdf}

Word Cloud - Beer Names

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Create the Word cloud of Beer Style}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{) }\CommentTok{# for reproducibility }
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ df_name}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ df_name}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \DecValTok{1}\NormalTok{,}\DataTypeTok{max.words=}\DecValTok{100}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{,}\DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{6}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-21-1.pdf}

We notice the most popular words are American, IPA and ALE.

Now we will run another test to check if the IPA and ALE have different
Mean for IBUs and ABV.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ale_ipa}\OperatorTok{$}\NormalTok{ipa_ale =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(ale_ipa}\OperatorTok{$}\NormalTok{ipa_ale)}
\KeywordTok{t.test}\NormalTok{(ale_ipa}\OperatorTok{$}\NormalTok{imputed_IBU }\OperatorTok{~}\NormalTok{ale_ipa}\OperatorTok{$}\NormalTok{ipa_ale)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  ale_ipa$imputed_IBU by ale_ipa$ipa_ale
## t = -42.582, df = 1095.1, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -39.37772 -35.90862
## sample estimates:
## mean in group ale mean in group ipa 
##          33.72304          71.36620
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(ale_ipa}\OperatorTok{$}\NormalTok{ABV }\OperatorTok{~}\NormalTok{ale_ipa}\OperatorTok{$}\NormalTok{ipa_ale)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  ale_ipa$ABV by ale_ipa$ipa_ale
## t = -19.143, df = 1070.2, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.01317336 -0.01072383
## sample estimates:
## mean in group ale mean in group ipa 
##        0.05659782        0.06854641
\end{verbatim}

Two sample t-test confirms that the mean of IBU and ABV is different for
ALE from IPA. This confirms our earlier inference from the KNN test.

Powered with this information, we tried to focus on the top 5 states in
the US in terms of consumption of beer.

The top 5 states in terms of beer consumption are California, Texas,
Florida, New York and Pennsylvania. referring to the report published at
\url{https://vinepair.com/articles/map-states-drink-beer-america-2020/}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Seperate ALE}
\NormalTok{ale =}\StringTok{ }\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(ipa_ale}\OperatorTok{==}\StringTok{"ale"}\NormalTok{)}

\CommentTok{# Seperate IPA}
\NormalTok{ipa =}\StringTok{ }\NormalTok{impute_data }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(ipa_ale}\OperatorTok{==}\StringTok{"ipa"}\NormalTok{)}


\CommentTok{# Step 1 -  group by state and count the number of beer in each state IPA and ALE }
\NormalTok{ipa_state =ipa }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(State)}
\NormalTok{ale_state =ale }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(State)}
\NormalTok{ale_state  =}\StringTok{ }\NormalTok{ale_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{rename}\NormalTok{(}\DataTypeTok{ALE =}\NormalTok{ n)}
\NormalTok{ipa_state  =}\StringTok{ }\NormalTok{ipa_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{rename}\NormalTok{(}\DataTypeTok{IPA =}\NormalTok{ n)}

\CommentTok{# Merge the Data Frame}
\NormalTok{beers_state =}\StringTok{ }\KeywordTok{merge}\NormalTok{(ale_state, ipa_state, }\DataTypeTok{by=}\StringTok{"State"}\NormalTok{)}


\CommentTok{# Step 2-  Filter for the top 5 states for Beer Consumption}
\NormalTok{beers_state_top_}\DecValTok{5}\NormalTok{=}\StringTok{ }\NormalTok{beers_state }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(State }\OperatorTok{==}\StringTok{ " CA"} \OperatorTok{|}\StringTok{ }\NormalTok{State}\OperatorTok{==}\StringTok{ " TX"} \OperatorTok{|}\StringTok{ }\NormalTok{State}\OperatorTok{==}\StringTok{ " FL"} \OperatorTok{|}\StringTok{ }\NormalTok{State}\OperatorTok{==}\StringTok{ " NY"} \OperatorTok{|}\StringTok{ }\NormalTok{State}\OperatorTok{==}\StringTok{ " PA"}\NormalTok{)}

\CommentTok{# Step 3-  Plot # of beers that are ale or ipa per state}
\NormalTok{beers_state_tall =}\StringTok{ }\NormalTok{beers_state_top_}\DecValTok{5} \OperatorTok{%>%}\StringTok{ }\KeywordTok{gather}\NormalTok{(}\DataTypeTok{key=}\NormalTok{ Beers, }\DataTypeTok{value=}\NormalTok{Value, ALE}\OperatorTok{:}\NormalTok{IPA)}
\NormalTok{beers_state_tall }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(State, Value, }\DataTypeTok{fill=}\NormalTok{Beers), ) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{position=}\StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_economist}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Beer Type for The Top 5 States (Consumption)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project1_eda_files/figure-latex/unnamed-chunk-23-1.pdf}

Based on the US census report. Texas is adding more population every
year than any other state in the USA.
\url{https://www.census.gov/newsroom/press-releases/2019/popest-nation.html}

In terms of Beer consumption Texas is at number 2 (as mentioned above).
Considering the growth in population and the beer consumption in Texas.
We recommend to launch new beer(s) in the state of Texas.

Considering there is a huge demand for IPA and Texas has lot less IPAs
compared to ALEs as shown the plot above. Since American, IPAs are most
popular beer styles, we recommend American Pale Ale (APA) or Indian Pale
Ale(IPA) for Texas market.

\end{document}
